- name: Install php-fpm and dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php5
    - php5-cli
    - php5-fpm
    - php5-mcrypt
    - php5-mysql
    - php5-curl
    - php-pear
    - php5-gd
    - php-apc
    - curl
    - postfix
    - vim
    - npm
    - git
  tags:
    - packages

- name: Install xdebug
  apt:
    name: php5-xdebug
    state: present
  when: debug

- name: Configure xdebug
  copy:
    src: xdebug.ini
    dest: /etc/php5/mods-available/xdebug.ini
  when: debug
  notify:
    - restart php5-fpm
    - restart nginx

- name: Disable default pool
  # Move the default pool if they haven't be moved.
  command: >
    mv
    {{ pool_dir }}/www.conf
    {{ pool_dir }}/www.disabled
    creates={{ pool_dir }}/www.disabled
  notify: restart php5-fpm

- name: Copy php-fpm configuration
  template:
    src: web.conf
    dest: "{{ pool_dir }}/www.conf"
  notify: restart php5-fpm

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
