- name: Create base directory
  file:
    state: directory
    path: /var/www
    owner: www-data
    group: www-data

- name: Link project
  file:
    state: link
    src: /vagrant
    dest: /var/www/current
    force: yes
    owner: www-data
    group: www-data

- name: Download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: "/tmp/installer"
  tags: composer

- name: Install composer
  shell: "cat /tmp/installer | php -- --install-dir=/usr/local/bin --filename=composer"
  args:
    creates: /usr/local/bin/composer
  tags: composer

- name: make composer executable
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file
  tags: composer

- name: Install sass
  command: gem install sass

- name: Install bower
  command: npm install -g bower

- name: Fix bower
  file:
    state: link
    src: /usr/bin/nodejs
    path: /usr/bin/node

- name: Change nginx user
  lineinfile:
    name: /etc/nginx/nginx.conf
    regexp: '^user'
    line: 'user vagrant;'

- name: Change php-fpm owner
  lineinfile:
    name: /etc/php5/fpm/pool.d/www.conf
    regexp: '^listen\.owner'
    line: 'listen.owner = vagrant'

- name: Change php-fpm group
  lineinfile:
    name: /etc/php5/fpm/pool.d/www.conf
    regexp: '^listen\.group'
    line: 'listen.group = vagrant'
    state: present

- name: Run composer
  command: composer install
  args:
    chdir: "{{ project_path }}"
  become: yes
  become_user: vagrant
