
- name: Create virtual hosts
  template:
    src: web.conf.j2
    dest: /etc/nginx/sites-available/filmoteca.unam.mx.conf
    owner: www-data
    group: www-data
  notify: restart nginx

- name: Enable virtual hosts
  file:
    state: link
    src: /etc/nginx/sites-available/filmoteca.unam.mx.conf
    dest: /etc/nginx/sites-enabled/filmoteca.unam.mx.conf
  notify: restart nginx

- name: Download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: "{{ project_path }}"
    mode: 0440

- name: Install composer
  shell: php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Installing dependencies
  command: composer install
  args:
    chdir: "{{project_path}}"
    creates: "{{project_path}}/vendor"
  become: yes
  become_user: www-data