- name: Install nginx
  apt:
    name: nginx
    state: present
  tags:
    - packages

- name: Uninstall apache
  apt:
    name: apache2
    state: absent
  tags:
    - packages

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create virtual hosts
  template:
    src: web.conf.j2
    dest: /etc/nginx/sites-available/filmoteca.unam.mx.conf
    owner: www-data
    group: www-data
  notify: restart nginx

- name: Enable virtual hosts
  file:
    state: link
    src: /etc/nginx/sites-available/filmoteca.unam.mx.conf
    dest: /etc/nginx/sites-enabled/filmoteca.unam.mx.conf
  notify: restart nginx