- name: migration
  hosts: mysql
  become: true
  tasks:
    - name: Move from /home to /var/www the website
      command: 'cp -R /home/{{ ansible_user }}/{{ environment_name }} /var/www'
      tags:
        - safe
    - name: Permissions to website
      file:
        state: directory
        path: '/var/www/{{ environment_name }}'
        owner: www-data
        group: www-data
        mode: 0755
        recurse: yes
      tags:
        - safe
    - name: Clean up migration
      command: 'rm -R /home/{{ ansible_user }}/{{ environment_name }}'
      tags:
        - unsafe
